import "./globals.css";
import type { Metadata } from "next";
import Topic from "@/models/topic";
import Link from "next/link";
import { Control } from "./Control";

export const metadata: Metadata = {
	title: "Web tutorial",
	description: "Generated by ji hyun kim",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	//next cache
	// cache: MISS - 캐시 만료 혹은 접근한 적 X
	// cache: HIT - 캐시에서 가져옴
	const response = await fetch(
		`${process.env.NEXT_PUBLIC_API_URL}/topics`,
		//방법1: 캐시 시간 0으로
		// { next: { revalidate: 0 } },
		//방법2: 캐시 사용 X
		{ cache: "no-store" }
	);
	const topics = await response.json();

	return (
		<html>
			<body>
				<h1>
					<a href="/">WEB</a>
				</h1>
				<ol>
					{topics.map((topic: Topic) => {
						return (
							<li key={topic.id}>
								<Link href={`/read/${topic.id}`}>{topic.title} </Link>
							</li>
						);
					})}
				</ol>
				{children}
				<Control />
			</body>
		</html>
	);
}
